### ISSUE TITLE
its broken. can not use it. i'm not good with computers

### ISSUE THREAD

**Issue by onc** [manly-man/moodle-destroyer-tools#10]
[Errno 2] No such file or directory: '/mnt/hdd/Hiwi/GdBS-16/.mdt/sync'
syncing assignments… called function: ['mod_assign_get_assignments']
finished. new: 0, updated: 0, unchanged: 14
syncing submissions… called function: ['mod_assign_get_submissions']
finished: wrote 0 new, 14 updates submission files
syncing grades… called function: ['mod_assign_get_grades']
finished. total: 12
syncing users… called function: ['core_enrol_get_enrolled_users']
onoz…
Please Report this Exception!
invalid_response_exception invalidresponse Ungültiger Rückgabewert gefunden preferences => Ungültiger Rückgabewert gefunden: name => Ungültiger Rückgabewert gefunden: Invalid external api response: the value is "message_provider_mod_organizer_appointment_reminder:student_loggedin", the server was expecting "alphanumext" type
Traceback (most recent call last):
  File "/home/onze/Applications/moodle-destroyer-tools/mdt.py", line 76, in <module>
    main()
  File "/home/onze/Applications/moodle-destroyer-tools/mdt.py", line 65, in main
    call()
  File "/home/onze/Applications/moodle-destroyer-tools/wstools.py", line 247, in sync
    _write_users(moodle, course_ids, wt)
  File "/home/onze/Applications/moodle-destroyer-tools/wstools.py", line 206, in _write_users
    reply = session.get_enrolled_users(course_id=cid)
  File "/home/onze/Applications/moodle-destroyer-tools/moodle/communication.py", line 160, in get_enrolled_users
    return self.post_web_service(data)
  File "/home/onze/Applications/moodle-destroyer-tools/moodle/communication.py", line 42, in post_web_service
    return self.post(self.url + self.ws_path, data)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 483, in send
    return self.build_response(request, resp)
  File "/home/onze/Applications/moodle-destroyer-tools/moodle/communication.py", line 303, in build_response
    self.handle_exception(data)
  File "/home/onze/Applications/moodle-destroyer-tools/moodle/communication.py", line 315, in handle_exception
    raise moodle.exceptions.MoodleError(**data)
moodle.exceptions.MoodleError: Please Report this Exception!
invalid_response_exception invalidresponse Ungültiger Rückgabewert gefunden preferences => Ungültiger Rückgabewert gefunden: name => Ungültiger Rückgabewert gefunden: Invalid external api response: the value is "message_provider_mod_organizer_appointment_reminder:student_loggedin", the server was expecting "alphanumext" type

**Comment by einsweniger** [comment]
This is caused by mod_organizer, can't do anything about it.
I wrote an exception for it, to handle it. 
Is reported [upstream](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/issues/24)
kthx
