### ISSUE TITLE
Issues using the software...

### ISSUE THREAD

**Issue by timofonic** [manly-man/moodle-destroyer-tools#17]
./mdt.py  auth https://iescampanillas.com/moodle
could not find global config, creating /home/timofonic/.config/mdtconfig

    The location of you moodle like "moodle.hostname.org/moodle"
    Moodle []: iescampanillas.com/moodle
    Your Moodle username []: timofonic

      Please insert your Moodle password.
      It will not be saved, it is required to get a token.
      Attention: keep your token safe until MDL-53400 is resolved.
      Until then it CANNOT be reset.
    Password:
onoz…
HTTPSConnectionPool(host='iescampanillas.com', port=443): Max retries exceeded w
ith url: /moodle/login/token.php (Caused by SSLError(SSLError("bad handshake: Er
ror([('SSL routines', 'tls_process_server_certificate', 'certificate verify fail
ed')],)",),))
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441
, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1716, in do_hands
hake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1456, in _raise_s
sl_error
    _raise_current_error()
  File "/usr/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exceptio
n_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certific
ate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, i
n urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, i
n _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, i
n _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 326, in co
nnect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl
_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 448
, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certi
ficate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in sen
d
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, i
n urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in in
crement
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='iescampanillas.com',
 port=443): Max retries exceeded with url: /moodle/login/token.php (Caused by SS
LError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_cert
ificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mdt.py", line 91, in <module>
    main()
  File "./mdt.py", line 77, in main
    func(**kwargs)
  File "/home/timofonic/src/git/moodle-destroyer-tools/frontend/commands.py", li
ne 73, in auth
    token = MoodleFrontend.get_token(settings[_url], settings[_user], password,
settings[_service])
  File "/home/timofonic/src/git/moodle-destroyer-tools/frontend/moodle.py", line 213, in get_token
    token = session.get_token(user_name=user, password=password, service=service)
  File "/home/timofonic/src/git/moodle-destroyer-tools/moodle/communication.py", line 78, in get_token
    response = self.post(self.url + endpoint, data)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='iescampanillas.com', port=443): Max retries exceeded with url: /moodle/login/token.php (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by namnatulco** [comment]
Your problem is that iescampanillas.com does not have a valid certificate. This causes your connection to be canceled, because otherwise your password might be stolen. I had a quick look at that page; it looks like the webserver configuration is completely broken (the HTTPS page refers to some servergrove web interface), and googling for this domain indicates that the domain is compromised. I would recommend that you contact your university system administrators -- having your university's main webpage marked as a malicious website in google is not exactly a good sign!
